from enum import IntEnum

NUM_CARDS = 52
CARD_FEATURES = 156
BETTING_FEATURES = 8
HISTORY_ACTIONS = 5
ACTION_TYPE_BITS = 5
HISTORY_FEATURES_PER_ACTION = 7
HISTORY_FEATURES = HISTORY_ACTIONS * HISTORY_FEATURES_PER_ACTION
STATE_DIM = CARD_FEATURES + BETTING_FEATURES + HISTORY_FEATURES

assert STATE_DIM == 199

N_ACTIONS = 5


class Street(IntEnum):
    PREFLOP = 0
    FLOP = 1
    TURN = 2
    RIVER = 3


class ActionBucket(IntEnum):
    FOLD = 0
    CHECK_CALL = 1
    BET_33 = 2
    BET_75 = 3
    ALL_IN = 4
